name: Build YTLitePlusEXTRA IPA
on:
  workflow_dispatch:
    inputs:
      enable_youpip:
        description: "Integrate YouPiP"
        type: boolean
        required: true
        default: true

      enable_ytuhd:
        description: "Integrate YTUHD"
        type: boolean
        required: true
        default: true

      enable_ryd:
        description: "Integrate Return YouTube Dislikes"
        type: boolean
        required: true
        default: true

      enable_demc:
        description: "Integrate DontEatMyContent"
        type: boolean
        required: true
        default: false

      enable_youtimestamp:
        description: "Integrate YouTimeStamp"
        type: boolean
        required: true
        default: true

      enable_ytabconfig:
        description: "Integrate YTABConfig"
        type: boolean
        required: true
        default: false

      enable_youloop:
        description: "Integrate YouLoop"
        type: boolean
        required: true
        default: true

      enable_youmute:
        description: "Integrate YouMute"
        type: boolean
        required: true
        default: false

      enable_youspeed:
        description: "Integrate YouSpeed"
        type: boolean
        required: true
        default: false

      enable_youslider:
        description: "Integrate YouSlider"
        type: boolean
        required: true
        default: false

      enable_youquality:
        description: "Integrate YouQuality"
        type: boolean
        required: true
        default: false

      enable_youchoose:
        description: "Integrate YouChooseQuality"
        type: boolean
        required: true
        default: false

      enable_youshare:
        description: "Integrate YouShare"
        type: boolean
        required: true
        default: false

      enable_gonerino:
        description: "Integrate Gonerino"
        type: boolean
        required: true
        default: false

      enable_ytsilentvote:
        description: "Integrate YTSilentVote"
        type: boolean
        required: true
        default: false

      ipa_url:
        description: "URL to the decrypted IPA file"
        default: ""
        required: true
        type: string

      ytlite_version:
        description: "YTLite Version (You can enter the version manually from YTLite releases or leave default.)"
        default: "5.2b4"
        required: true
        type: string

      display_name:
        description: "App Name (Optional)"
        default: "YouTube"
        required: true
        type: string

      bundle_id:
        description: "BundleID (Optional)"
        default: "com.google.ios.youtube"
        required: true
        type: string

      upload_artifact:
        description: "Upload IPA as an Artifact (Public)"
        default: true
        required: false
        type: boolean

      catbox_upload:
        description: "Upload IPA to Catbox.moe (URL)"
        default: true
        required: false
        type: boolean
        
      draft_release:
        description: "Create a draft release (Private)"
        default: true
        required: false
        type: boolean

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build YTLitePlusEXTRA IPA
    runs-on: macos-latest
    permissions:
      contents: write

    steps:
      - name: Check Inputs
        if: ${{ !inputs.upload_artifact && !inputs.draft_release && !inputs.catbox_upload }}
        run: |
          echo "No IPA output way selected. Please choose at least one."
          exit 1

      - name: Hide Sensitive Inputs
        uses: levibostian/action-hide-sensitive-inputs@v1
        with:
          exclude_inputs: bundle_id,display_name,ytlite_version,draft_release,upload_artifact,catbox_upload,enable_youpip,enable_ytuhd,enable_ryd,enable_demc,enable_youtimestamp,enable_ytabconfig,enable_youloop,enable_youmute,enable_youspeed,enable_youslider,enable_youquality,enable_youchoose,enable_youshare,enable_gonerino,enable_ytsilentvote
          
      - name: Download and Validate IPA
        run: |
          wget ${{ inputs.ipa_url }} --no-verbose -O youtube.ipa

          file_type=$(file --mime-type -b youtube.ipa)

          if [[ "$file_type" != "application/x-ios-app" && "$file_type" != "application/zip" ]]; then
            echo "::error::Validation failed: The downloaded file is not a valid IPA. Detected type: $file_type."
            exit 1
          fi

      - name: Get YouTube Version 
        run: |
          unzip -q youtube.ipa -d ytextracted
          echo "YT_VERSION=$(grep -A 1 '<key>CFBundleVersion</key>' ytextracted/Payload/YouTube.app/Info.plist | grep '<string>' | awk -F'[><]' '{print $3}')" >> $GITHUB_ENV
          echo -e 'Done!'

      - name: Install Dependencies
        run: brew install make ldid swiftlint

      - name: Set PATH Environment Variable
        run: echo "$(brew --prefix make)/libexec/gnubin" >> $GITHUB_PATH

      - name: Clone Theos
        run: git clone --quiet --recurse-submodules https://github.com/theos/theos.git
           
      - name: Download iOS SDK
        run: |
          git clone --quiet -n --depth=1 --filter=tree:0 https://github.com/Tonwalter888/iOS-18.6-SDK.git
          cd iOS-18.6-SDK
          git sparse-checkout set --no-cone iPhoneOS18.6.sdk
          git checkout
          mv *.sdk $THEOS/sdks
        env:
          THEOS: ${{ github.workspace }}/theos

      - name: Install cyan and tbd
        run: |
          pipx install --force https://github.com/asdfzxcvbn/pyzule-rw/archive/main.zip
          wget --no-verbose https://github.com/inoahdev/tbd/releases/download/2.2/tbd-mac -O /usr/local/bin/tbd
          chmod +x /usr/local/bin/tbd 

      - name: Download YTLite .deb
        run: wget https://github.com/dayanch96/YTLite/releases/download/v${{ inputs.ytlite_version }}/com.dvntm.ytlite_${{ inputs.ytlite_version }}_iphoneos-arm64.deb --no-verbose -O ytlite.deb

      - name: Clone Open in YouTube (Safari Extension)
        run: |
          git clone --quiet -n --depth=1 --filter=tree:0 https://github.com/BillyCurtis/OpenYouTubeSafariExtension.git
          cd OpenYouTubeSafariExtension
          git sparse-checkout set --no-cone OpenYouTubeSafariExtension.appex
          git checkout
          mv *.appex ${{ github.workspace }}

      - name: Clone YouTubeHeader
        run: |
           cd $THEOS/include
           git clone --quiet https://github.com/PoomSmart/YouTubeHeader.git
           cp -r "$THEOS/include/YouTubeHeader" "$THEOS/include/YTHeaders"
        env:
          THEOS: ${{ github.workspace }}/theos

      - name: Clone PSHeader
        run: |
           cd $THEOS/include
           git clone --quiet https://github.com/PoomSmart/PSHeader.git
        env:
          THEOS: ${{ github.workspace }}/theos

      - name: Clone YouPiP
        if: ${{ inputs.enable_youpip }}
        run: git clone --quiet https://github.com/PoomSmart/YouPiP.git
    
      - name: Clone YTUHD
        if: ${{ inputs.enable_ytuhd }}
        run: git clone --quiet https://github.com/Tonwalter888/YTUHD.git
           
      - name: Clone Return-YouTube-Dislikes
        if: ${{ inputs.enable_ryd }}
        run: git clone --quiet https://github.com/PoomSmart/Return-YouTube-Dislikes.git

      - name: Clone YouGroupSettings
        run: git clone --quiet https://github.com/PoomSmart/YouGroupSettings.git
           
      - name: Clone YTVideoOverlay
        run: git clone --quiet https://github.com/PoomSmart/YTVideoOverlay.git
          
      - name: Clone YTABConfig
        if: ${{ inputs.enable_ytabconfig }}
        run: git clone --quiet https://github.com/PoomSmart/YTABConfig.git
                  
      - name: Clone YouQuality
        if: ${{ inputs.enable_youquality }}
        run: git clone --quiet https://github.com/PoomSmart/YouQuality.git

      - name: Clone YouSpeed
        if: ${{ inputs.enable_youspeed }}
        run: git clone --quiet https://github.com/PoomSmart/YouSpeed.git

      - name: Clone DontEatMyContent
        if: ${{ inputs.enable_demc }}
        run: git clone --quiet https://github.com/therealFoxster/DontEatMyContent.git

      - name: Clone YouMute
        if: ${{ inputs.enable_youmute }}
        run: git clone --quiet https://github.com/PoomSmart/YouMute.git

      - name: Clone YTABGoodies
        run: git clone --quiet https://github.com/PoomSmart/YTABGoodies.git

      - name: Clone YouTimeStamp
        if: ${{ inputs.enable_youtimestamp }}
        run: git clone --quiet https://github.com/Tonwalter888/YouTimeStamp.git
    
      - name: Clone YouLoop
        if: ${{ inputs.enable_youloop }}
        run: git clone --quiet https://github.com/Tonwalter888/YouLoop.git

      - name: Clone Alderis
        run: git clone --quiet https://github.com/hbang/Alderis.git

      - name: Clone YouSlider
        if: ${{ inputs.enable_youslider }}
        run: git clone --quiet https://github.com/PoomSmart/YouSlider.git

      - name: Clone YouChooseQuality
        if: ${{ inputs.enable_youchoose }}
        run: git clone --quiet https://github.com/PoomSmart/YouChooseQuality.git

      - name: Clone YTSilentVote
        if: ${{ inputs.enable_ytsilentvote }}
        run: git clone --quiet https://github.com/PoomSmart/YTSilentVote.git

      - name: Clone YouShare
        if: ${{ inputs.enable_youshare }}
        run: git clone --quiet https://github.com/Tonwalter888/YouShare.git

      - name: Clone Gonerino
        if: ${{ inputs.enable_gonerino }}
        run: git clone --quiet https://github.com/castdrian/Gonerino.git
      
      - name: Build YouPiP
        if: ${{ inputs.enable_youpip }}
        run: |
          cd YouPiP
          make clean package DEBUG=0 FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless
          mv packages/*.deb ${{ github.workspace }}/youpip.deb
        env:
          THEOS: ${{ github.workspace }}/theos    

      - name: Build YTUHD
        if: ${{ inputs.enable_ytuhd }}
        run: |
          cd YTUHD
          make clean package DEBUG=0 FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless
          mv packages/*.deb ${{ github.workspace }}/ytuhd.deb
        env:
          THEOS: ${{ github.workspace }}/theos

      - name: Build Return-YouTube-Dislikes
        if: ${{ inputs.enable_ryd }}
        run: |
          cd Return-YouTube-Dislikes
          make clean package DEBUG=0 FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless
          mv packages/*.deb ${{ github.workspace }}/ryd.deb
        env:
          THEOS: ${{ github.workspace }}/theos

      - name: Build YouGroupSettings
        run: |
          cd YouGroupSettings
          make clean package DEBUG=0 FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless
          mv packages/*.deb ${{ github.workspace }}/ygs.deb
        env:
          THEOS: ${{ github.workspace }}/theos

      - name: Build YTVideoOverlay
        run: |
          cd YTVideoOverlay
          make clean package DEBUG=0 FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless
          mv packages/*.deb ${{ github.workspace }}/ytvo.deb
        env:
          THEOS: ${{ github.workspace }}/theos

      - name: Build YTABConfig
        if: ${{ inputs.enable_ytabconfig }}
        run: |
          cd YTABConfig
          make clean package DEBUG=0 FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless
          mv packages/*.deb ${{ github.workspace }}/ytabconfig.deb
        env:
          THEOS: ${{ github.workspace }}/theos

      - name: Build YouQuality
        if: ${{ inputs.enable_youquality }}
        run: |
          cd YouQuality
          make clean package DEBUG=0 FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless
          mv packages/*.deb ${{ github.workspace }}/youquality.deb
        env:
          THEOS: ${{ github.workspace }}/theos

      - name: Build YouSpeed
        if: ${{ inputs.enable_youspeed }}
        run: |
          cd YouSpeed
          make clean package DEBUG=0 FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless
          mv packages/*.deb ${{ github.workspace }}/youspeed.deb
        env:
          THEOS: ${{ github.workspace }}/theos

      - name: Build DontEatMyContent
        if: ${{ inputs.enable_demc }}
        run: |
          cd DontEatMyContent
          make clean package DEBUG=0 FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless
          mv packages/*.deb ${{ github.workspace }}/demc.deb
        env:
          THEOS: ${{ github.workspace }}/theos

      - name: Build YouMute
        if: ${{ inputs.enable_youmute }}
        run: |
          cd YouMute
          make clean package DEBUG=0 FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless
          mv packages/*.deb ${{ github.workspace }}/ym.deb
        env:
          THEOS: ${{ github.workspace }}/theos 

      - name: Build YTABGoodies
        run: |
          cd YTABGoodies
          make clean package DEBUG=0 FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless
          mv packages/*.deb ${{ github.workspace }}/ytgoodab.deb
        env:
          THEOS: ${{ github.workspace }}/theos

      - name: Build YouTimeStamp
        if: ${{ inputs.enable_youtimestamp }}
        run: |
          cd YouTimeStamp
          make clean package DEBUG=0 FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless
          mv packages/*.deb ${{ github.workspace }}/youts.deb
        env:
          THEOS: ${{ github.workspace }}/theos

      - name: Build YouLoop
        if: ${{ inputs.enable_youloop }}
        run: |
          cd YouLoop
          make clean package DEBUG=0 FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless
          mv packages/*.deb ${{ github.workspace }}/youloop.deb
        env:
          THEOS: ${{ github.workspace }}/theos

      - name: Build YouSlider
        if: ${{ inputs.enable_youslider }}
        run: |
          cd YouSlider
          make clean package DEBUG=0 FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless
          mv packages/*.deb ${{ github.workspace }}/youslider.deb
        env:
          THEOS: ${{ github.workspace }}/theos

      - name: Build Alderis
        run: |
          cd Alderis
          make clean package DEBUG=0 FINALPACKAGE=1
          mv packages/*.deb ${{ github.workspace }}/alderis.deb
        env:
          THEOS: ${{ github.workspace }}/theos

      - name: Build YouChooseQuality
        if: ${{ inputs.enable_youchoose }}
        run: |
          cd YouChooseQuality
          make clean package DEBUG=0 FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless
          mv packages/*.deb ${{ github.workspace }}/youchoose.deb
        env:
          THEOS: ${{ github.workspace }}/theos

      - name: Build YTSilentVote
        if: ${{ inputs.enable_ytsilentvote }}
        run: |
          cd YTSilentVote
          make clean package DEBUG=0 FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless
          mv packages/*.deb ${{ github.workspace }}/ytnovote.deb
        env:
          THEOS: ${{ github.workspace }}/theos  

      - name: Build YouShare
        if: ${{ inputs.enable_youshare }}
        run: |
          cd YouShare
          make clean package DEBUG=0 FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless
          mv packages/*.deb ${{ github.workspace }}/youshare.deb
        env:
          THEOS: ${{ github.workspace }}/theos
          
      - name: Build Gonerino
        if: ${{ inputs.enable_gonerino }}
        run: |
          cd Gonerino
          make clean package DEBUG=0 FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless
          mv packages/*.deb ${{ github.workspace }}/gonerino.deb
        env:
          THEOS: ${{ github.workspace }}/theos
  
      - name: Inject Tweaks Into IPA
        run: |
          tweaks="ytlite.deb OpenYouTubeSafariExtension.appex"

          for f in *.deb; do
            if [ -f "$f" ]; then
              tweaks="$tweaks $f"
            fi
          done
          
          cyan -i youtube.ipa -o YTLitePlusEXTRA_${{ env.YT_VERSION }}_v${{ inputs.ytlite_version }}.ipa -uwef $tweaks -n "${{ inputs.display_name }}" -b ${{ inputs.bundle_id }}

      - name: Upload IPA to Catbox
        if: ${{ inputs.catbox_upload }}
        run: |
          RESPONSE=$(curl -F "reqtype=fileupload" -F "fileToUpload=@YTLitePlusEXTRA_${{ env.YT_VERSION }}_v${{ inputs.ytlite_version }}.ipa" https://catbox.moe/user/api.php)
          CATBOX_URL=$(echo $RESPONSE | grep -o -E 'https://files.catbox.moe/[^"]*')
          echo "Uploaded artifact to $CATBOX_URL"
          CATBOX_FILE=$(echo $CATBOX_URL | sed 's|https://files.catbox.moe/||')
          echo "CATBOX_FILE=$CATBOX_FILE" >> $GITHUB_ENV
          echo "CATBOX_URL=$CATBOX_URL" >> $GITHUB_ENV

      - name: Upload IPA as an Artifact
        if: ${{ inputs.upload_artifact }}
        uses: actions/upload-artifact@v5
        with:
          name: YTLitePlusEXTRA_${{ env.YT_VERSION }}_v${{ inputs.ytlite_version }}
          path: YTLitePlusEXTRA_${{ env.YT_VERSION }}_v${{ inputs.ytlite_version }}.ipa

      - name: Create a Draft Release
        if: ${{ inputs.draft_release }}
        uses: softprops/action-gh-release@v2.4.2
        with:
          tag_name: ytliteplusextra-ipa${{ github.run_number }}
          name: YTLitePlusEXTRA_${{ env.YT_VERSION }}_v${{ inputs.ytlite_version }} (${{ github.run_number }}) 
          files: YTLitePlusEXTRA_${{ env.YT_VERSION }}_v${{ inputs.ytlite_version }}.ipa
          draft: true

      - name: Job Summary - Build Complete
        run: |
          echo -e '### ðŸ› ï¸ Build YTLitePlusEXTRA IPA Complete!' >> $GITHUB_STEP_SUMMARY

      - name: Job Summary - Output the Artifact Upload
        if: ${{ inputs.upload_artifact }}
        run: |
          echo -e '### ðŸ“¦ Artifact Upload\n\nUpload IPA as an artifact successfully! Refresh and [Scroll down](#artifacts) to view the artifact. Note that you must be signed in to GitHub to download it.' >> $GITHUB_STEP_SUMMARY

      - name: Job Summary - Output the IPA URL (Catbox Upload)
        if: ${{ inputs.catbox_upload }}
        run: |
          echo -e '### ðŸ± Catbox Upload\n\nUpload IPA to Catbox successfully! Here is a permanent shareable link: '$CATBOX_URL >> $GITHUB_STEP_SUMMARY

      - name: Job Summary - Output a Draft Release Link
        if: ${{ inputs.draft_release }}
        run: |
          echo -e '### ðŸš€ Draft Release\n\nDraft release has been created successfully! You can view your release here: https://github.com/${{ github.repository }}/releases' >> $GITHUB_STEP_SUMMARY
     
      - name: Job Summary - Cleanup
        run: |
          echo -e '### ðŸ§¹ Cleanup\n\nYou can remove previous GitHub Actions run here: https://github.com/${{ github.repository }}/actions/workflows/delete-old-workflows-run.yml And if you want to delelte old draft releases you have then here: https://github.com/${{ github.repository }}/actions/workflows/delete-old-draft-releases.yml' >> $GITHUB_STEP_SUMMARY
